import streamlit as st
import google.generativeai as genai
from pptx import Presentation
import io

# Setup API
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    model = genai.GenerativeModel('gemini-pro')
except:
    st.error("Check your Secret Key in Streamlit settings!")

st.title("Kobby's Slide Generator 🚀")

topic = st.text_input("What is your presentation about?", placeholder="e.g. Logistics in Kumasi")

if st.button("Generate PowerPoint"):
    if topic:
        with st.spinner("Writing content with AI..."):
            # 1. Ask AI for slide content
            prompt = f"Create a 5-slide outline for a presentation on {topic}. For each slide, give me a Title and 3 bullet points."
            response = model.generate_content(prompt)
            
            # 2. Create the PowerPoint file in memory
            prs = Presentation()
            
            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = topic
            slide.placeholders[1].text = "Generated by Kobby's AI App"

            # Content Slide (Simplified for this version)
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = "Presentation Outline"
            slide.placeholders[1].text = response.text

            # 3. Prepare file for download
            binary_output = io.BytesIO()
            prs.save(binary_output)
            
            st.success("Done!")
            st.download_button(
                label="Click here to Download PPTX",
                data=binary_output.getvalue(),
                file_name=f"{topic}_presentation.pptx",
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            )
    else:
        st.warning("Please enter a topic first!")
