import streamlit as st
import google.generativeai as genai
from pptx import Presentation
import io

# 1. Setup API with the latest model
try:
    # This pulls your key from the 'Secrets' we set up
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    # Using 1.5-flash for better speed and stability
    model = genai.GenerativeModel('gemini-1.5-flash')
except Exception as e:
    st.error("Missing API Key! Please add it to your Streamlit Secrets.")

st.set_page_config(page_title="Kobby's Slide Generator", page_icon="🚀")

st.title("Kobby's Slide Generator 🚀")
st.write("Professional slides for Business and Logistics students.")

topic = st.text_input("What is your presentation about?", placeholder="e.g. Supply Chain Management in Ghana")

if st.button("Generate PowerPoint"):
    if topic:
        with st.spinner("AI is thinking..."):
            try:
                # 2. Ask AI for structured content
                prompt = f"Create a 5-slide outline for {topic}. For each slide, provide a Title and 3 bullet points. Keep it professional."
                response = model.generate_content(prompt)
                
                # 3. Build the PowerPoint file
                prs = Presentation()
                
                # Title Slide
                title_slide_layout = prs.slide_layouts[0]
                slide = prs.slides.add_slide(title_slide_layout)
                slide.shapes.title.text = topic
                slide.placeholders[1].text = "Generated by Kobby's Developer Tool"

                # Content Slide
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                slide.shapes.title.text = "Key Points"
                slide.placeholders[1].text = response.text

                # 4. Save to memory for download
                binary_output = io.BytesIO()
                prs.save(binary_output)
                
                st.success("Your presentation is ready!")
                st.download_button(
                    label="📥 Download .pptx File",
                    data=binary_output.getvalue(),
                    file_name=f"{topic.replace(' ', '_')}.pptx",
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
                )
            except Exception as e:
                st.error(f"An error occurred: {e}")
                st.info("Try refreshing the page or checking your API key.")
    else:
        st.warning("Please enter a topic first!")

st.divider()
st.caption("Developed by Kobby Klench | KNUST Business Administration")
