import streamlit as st
import google.generativeai as genai
from pptx import Presentation
import io

# 1. Setup API with Error Handling
try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    # Using 'gemini-pro' as it is the most widely supported standard name
    model = genai.GenerativeModel('gemini-pro')
except Exception as e:
    st.error("Credential Error: Please check your Streamlit Secrets.")

st.set_page_config(page_title="Kobby's Slide Generator", page_icon="🚀")

st.title("Kobby's Slide Generator 🚀")
st.write("Professional tools for Business and Logistics students.")

topic = st.text_input("What is your presentation about?", placeholder="e.g. Supply Chain in Ghana")

if st.button("Generate PowerPoint"):
    if topic:
        with st.spinner("AI is generating your content..."):
            try:
                # 2. Ask AI for content
                prompt = f"Write a professional 5-slide presentation about {topic}. For each slide, provide a Title and 3 bullet points."
                response = model.generate_content(prompt)
                
                # 3. Build the PowerPoint file
                prs = Presentation()
                
                # Title Slide
                title_slide_layout = prs.slide_layouts[0]
                slide = prs.slides.add_slide(title_slide_layout)
                slide.shapes.title.text = topic
                slide.placeholders[1].text = "Generated by Kobby's Developer Tool"

                # Content Slide
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                slide.shapes.title.text = "Presentation Summary"
                slide.placeholders[1].text = response.text

                # 4. Save for download
                binary_output = io.BytesIO()
                prs.save(binary_output)
                
                st.success("Success!")
                st.download_button(
                    label="📥 Download PowerPoint",
                    data=binary_output.getvalue(),
                    file_name=f"{topic.replace(' ', '_')}.pptx",
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
                )
            except Exception as e:
                st.error(f"Technical Error: {e}")
                st.info("Tip: Double-check that your new API key is correctly pasted in the Secrets tab.")
    else:
        st.warning("Please enter a topic first!")

st.divider()
st.caption("Developed by Kobby Klench | KNUST Business Administration")
